M48
; DRILL file {KiCad 7.0.6} date Tue Jul  8 02:34:13 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-08T02:34:13-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0469
%
G90
G05
T1
X1.9236Y-2.1216
T2
X2.2386Y-1.7672
X2.2386Y-1.8672
T0
M30
