M48
; DRILL file {KiCad 7.0.6} date Mon Jun 23 03:39:35 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-23T03:39:35-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0469
%
G90
G05
T1
X4.2126Y-4.0748
T2
X4.5276Y-3.7205
X4.5276Y-3.8205
T0
M30
